[package]
name = "updates_commands_rust"
version = "0.1.0"
<<<<<<< HEAD
=======
by = "Obaid Aldosari"
github = "https://github.com/ODosari/UpdatesTerminalCommandsRust"
>>>>>>> 2fbc2ce (Initial commit)
edition = "2021"

[dependencies]
ansi_term = "0.12.1"